#!/bin/bash
echo "=== Contact for LID 91268138926223 ==="
psql -U postgres -d marketplacejamaah -c "SELECT id, phone_number, name, is_registered, is_blocked, onboarding_status FROM contacts WHERE phone_number = '91268138926223';"
echo ""
echo "=== Contact for master 6285719195627 ==="
psql -U postgres -d marketplacejamaah -c "SELECT id, phone_number, name, is_registered, is_blocked, onboarding_status FROM contacts WHERE phone_number = '6285719195627';"
echo ""
echo "=== Agent logs for latest Bantuan messages ==="
psql -U postgres -d marketplacejamaah -c "SELECT id, agent_name, message_id, status, error, created_at FROM agent_logs WHERE message_id IN (787, 788, 789) ORDER BY id;"
echo ""
echo "=== Failed jobs ==="  
psql -U postgres -d marketplacejamaah -c "SELECT id, payload::text, failed_at FROM failed_jobs ORDER BY id DESC LIMIT 3;"
echo ""
echo "=== Queue pending ==="
psql -U postgres -d marketplacejamaah -c "SELECT COUNT(*) as pending FROM jobs;"
